environment:
  name: staging
  server: https://replace-with-staging-cluster-endpoint
  gitopsRepository: https://github.com/devSatym/gcp-platform-engineering.git
  policy:
    automatedSync: true
    prune: true
    selfHeal: true
    rolloutProfile: validation
