installCRDs: true
serviceAccount:
  create: true
  name: external-secrets
tolerations:
  - key: workload
    operator: Equal
    value: system
    effect: NoSchedule
nodeSelector:
  workload: system
webhook:
  tolerations:
    - key: workload
      operator: Equal
      value: system
      effect: NoSchedule
  nodeSelector:
    workload: system
certController:
  tolerations:
    - key: workload
      operator: Equal
      value: system
      effect: NoSchedule
  nodeSelector:
    workload: system
