environment:
  name: prod
  server: https://replace-with-prod-cluster-endpoint
  gitopsRepository: https://github.com/devSatym/gcp-platform-engineering.git
  policy:
    automatedSync: false
    prune: false
    selfHeal: true
    rolloutProfile: guarded
