#!/usr/bin/env bash
# Wait for the Applications generated by this repository's GitOps contracts.
# The script is read-only and is safe to use as Terraform's final bootstrap
# gate after the root Argo CD Application has been created.

set -Eeuo pipefail

readonly DEFAULT_ENVIRONMENT="dev"
readonly DEFAULT_TIMEOUT_SECONDS=1800
readonly ARGOCD_NAMESPACE="argocd"

environment="${DEFAULT_ENVIRONMENT}"
timeout_seconds="${DEFAULT_TIMEOUT_SECONDS}"
kube_context=""

usage() {
  cat <<'EOF'
Usage: scripts/wait-for-gitops-convergence.sh [options]

Wait until the root, platform, and workload Applications generated from the
repository contracts are all Synced and Healthy.

Options:
  -e, --environment NAME    Environment name (default: dev).
  -t, --timeout SECONDS     Maximum wait time, 300-3600 (default: 1800).
  -c, --context NAME        Kubernetes context to use.
  -h, --help                Show this help text.
EOF
}

die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

while (($# > 0)); do
  case "$1" in
    -e|--environment)
      (($# >= 2)) || die "${1} requires an environment name."
      environment="$2"
      shift 2
      ;;
    -t|--timeout)
      (($# >= 2)) || die "${1} requires a timeout in seconds."
      timeout_seconds="$2"
      shift 2
      ;;
    -c|--context)
      (($# >= 2)) || die "${1} requires a Kubernetes context."
      kube_context="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown option: $1"
      ;;
  esac
done

[[ "$environment" =~ ^[a-z][a-z0-9-]{0,61}[a-z0-9]$ ]] || die "environment must be a lowercase DNS-style identifier."
[[ "$timeout_seconds" =~ ^[0-9]+$ ]] || die "timeout must be an integer number of seconds."
((timeout_seconds >= 300 && timeout_seconds <= 3600)) || die "timeout must be between 300 and 3600 seconds."

command -v kubectl >/dev/null 2>&1 || die "kubectl must be installed and on PATH."

declare -a kubectl_cmd=(kubectl)
if [[ -n "$kube_context" ]]; then
  kubectl_cmd+=(--context "$kube_context")
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
declare -a expected_apps=("root" "projects" "platform-core-${environment}")

while IFS= read -r -d '' contract; do
  name="$(sed -n 's/^  name: \([^[:space:]#][^[:space:]#]*\).*/\1/p' "$contract" | head -n 1)"
  [[ -n "$name" ]] || die "Unable to read a component name from ${contract#$repo_root/}."
  expected_apps+=("${name}-${environment}")
done < <(find "$repo_root/gitops" -mindepth 2 -maxdepth 2 -name component.yaml -print0 | sort -z)

while IFS= read -r -d '' contract; do
  name="$(sed -n 's/^  name: \([^[:space:]#][^[:space:]#]*\).*/\1/p' "$contract" | head -n 1)"
  [[ -n "$name" ]] || die "Unable to read a workload name from ${contract#$repo_root/}."
  expected_apps+=("${name}-${environment}")
done < <(find "$repo_root/gitops/workloads" -mindepth 2 -maxdepth 2 -name workload.yaml -print0 | sort -z)

mapfile -t expected_apps < <(printf '%s\n' "${expected_apps[@]}" | sort -u)
deadline=$((SECONDS + timeout_seconds))
last_report_at=-30

printf 'Waiting for %s GitOps Applications in environment %s...\n' "${#expected_apps[@]}" "$environment"

while ((SECONDS < deadline)); do
  declare -a pending=()

  for app in "${expected_apps[@]}"; do
    if ! status="$("${kubectl_cmd[@]}" -n "$ARGOCD_NAMESPACE" get application "$app" -o jsonpath='{.status.sync.status}{"/"}{.status.health.status}' 2>/dev/null)"; then
      pending+=("${app}=not-created")
      continue
    fi

    if [[ "$status" != "Synced/Healthy" ]]; then
      pending+=("${app}=${status:-unknown}")
    fi
  done

  if ((${#pending[@]} == 0)); then
    printf 'GitOps convergence complete: all %s Applications are Synced and Healthy.\n' "${#expected_apps[@]}"
    exit 0
  fi

  if ((SECONDS - last_report_at >= 30)); then
    printf 'Still converging: %s\n' "$(IFS=', '; printf '%s' "${pending[*]}")"
    last_report_at=$SECONDS
  fi
  sleep 5
done

printf 'Timed out after %ss. Current Application state:\n' "$timeout_seconds" >&2
for app in "${expected_apps[@]}"; do
  status="$("${kubectl_cmd[@]}" -n "$ARGOCD_NAMESPACE" get application "$app" -o jsonpath='{.status.sync.status}{"/"}{.status.health.status}{"/"}{.status.operationState.phase}' 2>/dev/null || printf 'not-created')"
  printf '  %s: %s\n' "$app" "$status" >&2
done
exit 1
